# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_issue', models.CharField(choices=[('Food', 'Food'), ('House Keeping', 'House Keeping'), ('Electrical', 'Electrical')], max_length=200)),
                ('issue', models.CharField(max_length=1000)),
                ('issue_open_date', models.DateField()),
                ('issue_close_date', models.DateField()),
                ('issue_user_close', models.IntegerField(default=0)),
                ('issue_maintenance_close', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('user_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='complainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issue.User'),
        ),
    ]
