# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-25 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_auto_20160325_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_close_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_open_date',
            field=models.DateTimeField(),
        ),
    ]
